synonymdev/bitkit-android

settings.gradle.kts
This PR fixes failing builds on new machines which has no dependencies cache.
This command should work after removing all local gradle/maven dependency caches:
```
./gradlew --refresh-dependencies clean assembleDevDebug
```
It was failing for our own dependencies served via jitpack:
- bitkit-core
- ldk-node (synonym fork)
=> Fix build dependency resolution when cache is missing

app/src/main/java/to/bitkit/env/Env.kt, app/src/main/java/to/bitkit/repositories/BlocktankRepo.kt, app/src/main/java/to/bitkit/repositories/WalletRepo.kt, app/src/main/java/to/bitkit/services/LightningService.kt, app/src/main/java/to/bitkit/ui/components/Spacers.kt, app/src/main/java/to/bitkit/ui/screens/transfer/external/LnurlChannelScreen.kt, app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt, gradle/libs.versions.toml
This PR adds configuration to test ldk-node with authenticated VSS implementation using LNURL-auth server endpoint issuing JWT tokens.
- vss auth config setup
- update ldk-node and adapt max send amount calculation to use the fixed method
- fix lnurl channel screen spacing
- upgrade agp to latest android-studio version
- deploy [vss-server](https://github.com/ovitrif/vss-server/) and a LNURL-auth JWT-issuing service like the one in [bitkit-docker](https://github.com/ovitrif/bitkit-docker) to staging
- adapt [vss-rust-client-ffi](https://github.com/synonymdev/vss-rust-client-ffi) to manage auth via `lnurlAuthServerUrl` like it’s done by `ldk-node` via `build_with_vss_store`
- see [bitkit-docker LDK-NODE with JWT auth to VSS](https://github.com/ovitrif/bitkit-docker?tab=readme-ov-file#ldk-no …
=> LDK-node JWT auth to VSS rust

app/src/main/java/to/bitkit/data/dto/PendingBoostActivity.kt, app/src/main/java/to/bitkit/ext/Activities.kt, app/src/main/java/to/bitkit/repositories/ActivityRepo.kt, app/src/main/java/to/bitkit/ui/screens/wallets/activity/BoostTransactionViewModel.kt, app/src/main/java/to/bitkit/ui/screens/wallets/activity/components/ActivityIcon.kt, app/src/test/java/to/bitkit/repositories/ActivityRepoTest.kt, app/src/test/java/to/bitkit/ui/screens/wallets/activity/BoostTransactionViewModelTest.kt
Related to #268 
This PR implements some changes to the Boost logic to give the user faster feedback
https://github.com/user-attachments/assets/0f25194e-101e-4e87-a760-518c3fd5d9b9
https://github.com/user-attachments/assets/9c87c609-2bce-4857-8634-5f21f3bc5eee
- RBF flow
- CPFP flow
=> Boost UX improvements

gradle.properties
This PR enables the gradle configuration cache.
This feature focuses on an earlier part of the build process: the configuration phase. During this phase, Gradle reads your build.gradle files, determines the project structure, and creates the graph of tasks to be executed.
With the configuration cache enabled, Gradle saves a snapshot of this task graph.
On subsequent builds, if your build scripts or project settings haven't changed, Gradle can skip the entire configuration phase and reuse the cached task graph. This can lead to a significant time savings, especially in large, multi-module projects where the configuration phase can be time-consuming.
[Reference](https://docs.gradle.org/current/userguide/configuration_cache.html)
`n/a`
`n/a`
=> Gradle config cache

app/src/main/java/to/bitkit/ui/MainActivity.kt, app/src/main/java/to/bitkit/ui/sheets/NewTransactionSheet.kt
This PR injects the SettingsViewModel to fix the amount visibility bug
https://github.com/user-attachments/assets/4eccea56-5a6a-4921-9720-98ab2aea6398
- Send or receive bitcoin
=> Display amount in Transaction Sheet

app/src/main/java/to/bitkit/repositories/ActivityRepo.kt, app/src/main/java/to/bitkit/ui/ContentView.kt, app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt, app/src/test/java/to/bitkit/ui/sheets/BoostTransactionViewModelTest.kt
The LDK-node re-triggers the last event at startup. This checks if the activity is not already saved before displaying the receive sheet.
https://github.com/user-attachments/assets/3dff55aa-3f39-4628-8ecb-26e8b2f1f270
https://github.com/user-attachments/assets/c9bd2273-1f48-46e3-8105-0d018738b355
Tested flows:
- Send bitcoin -> should display the sheet -> restart the app -> shouldn't display the sheet
- Receive bitcoin -> should display the sheet -> restart the app -> shouldn't display the sheet
OBS: I noticed that the sheets are not displaying the amount. I'll investigate it in the next PR
=> Don't trigger repeated payment events

app/src/main/java/to/bitkit/ui/screens/wallets/HomeScreen.kt, app/src/main/java/to/bitkit/ui/screens/wallets/HomeViewModel.kt
This PR re-enables the edit widgtet button
https://github.com/user-attachments/assets/a7169bf6-054f-4f39-858e-c7a35744bc66
1. Go to settings -> enable widgets
2. Navigate to home -> click in edit widgets -> click in the confirm button
=> fix: re-enable button edit widgets

app/src/main/java/to/bitkit/ui/onboarding/RestoreWalletScreen.kt
Adding a test id that was missing for onboarding with mnemonic restore.
=> Add missing word-$index testId

app/src/main/java/to/bitkit/ui/components/Spacers.kt, app/src/main/java/to/bitkit/ui/screens/transfer/SpendingAmountScreen.kt, app/src/main/java/to/bitkit/viewmodels/TransferViewModel.kt
Some Blocktank methods need  the node running to work properly
https://github.com/user-attachments/assets/ba02f8ee-82c3-4f8a-9fe8-15b94a2aa216
Tested:
=> Wait for node starts in SpendingAmountScreen

app/src/main/java/to/bitkit/App.kt, app/src/main/java/to/bitkit/androidServices/LightningNodeService.kt, app/src/main/java/to/bitkit/data/backup/VssStoreIdProvider.kt, app/src/main/java/to/bitkit/env/Env.kt, app/src/main/java/to/bitkit/ui/components/IsOnlineTracker.kt, gradle/libs.versions.toml
Related:
- https://github.com/synonymdev/vss-rust-client-ffi/pull/3
This PR updates to latest vss client version and uses its new api to derive a deterministic vss store id, unique per wallet.
- chore: update env comment to use new lnurl-auth-server url
- feat: get store id from vss client rust lib
- fix: remove app from recents when stopped via notif buttonminutes ago
- fix: restore IsOnlineTracker startup toast prevention
Test case:
- wallet create
- fund
- transfer to spending (to add LN channel)
- change settings & widgets data
- backup mnemonic
- reset / wipe / uninstall
- restore wallet
- expect ldk-node & settings + widgets data restored successfully
=> feat: use vss client to derive store id

app/src/main/java/to/bitkit/ui/screens/wallets/activity/components/ActivityAddTagSheet.kt
The test tags (i.e. `resource-ids`) where not visible in the add tag screen until explicitely adding `.semantics { testTagsAsResourceId = true } ` in this particular component function, that is used on the screen. Probably this component not created/rendered from the main scope where `testTagsAsResourceId = true` is set globally. Maybe there is a better way to do this, but this fixes the problem and `resource-id` is now rendered.
=> Make tagInputTestTag and addButtonTestTag visible

app/src/main/java/to/bitkit/ui/screens/wallets/send/SendAddressScreen.kt
This PR changes the keyboard action button on input send address form to `Done` instead default `Enter` which did not incur any action. After the change confirmation closes the keyboard.
This is inline with Bitkit RN.
Before:
After:
Tested manually and while preparing e2e test for `onchain` test suite on emulator.
=> Keyboard with ImeAction.Done on entering send address

.github/workflows/e2e.yml
Allow specifying e2e tests branch in e2e workflow in workflow-dispatch. By default `main` should be used from `synonymdev/bitkit-e2e-tests`.
=> Allow specifying e2e branch

app/src/main/java/to/bitkit/ui/screens/wallets/send/SendConfirmScreen.kt, app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt
Closes #325, Closes #328
This PR fixes the fee above 10 USD sanity check. The method was using the full sending amount instead of just the fee value.
Also check all the sanity checks instead of skipping the others after confirming the first one
https://github.com/user-attachments/assets/96cd3d36-efb1-41f0-9553-c6af05f05120
https://github.com/user-attachments/assets/e54ca921-e766-48b7-b129-a17d0e1b7e60
Steps to reproduce:
1. Have ₿ 100 000 000 in the wallet.
2. Send ₿ 51 000 000 and swipe to confirm, i.e., over 50% of funds.
3. Notice the sending over 50% of balance warning pop-up appearing.
4. Cancel the tx.
5. Enable the warning for sending over 100$. (Settings > Security and Privacy > Warn when sending over $100)
6. Go back and send again ₿ 51 000 000. Swipe to confirm.
7. Notice the …
=> fix: Fee above 10 USD sanity check and don't skip checks

app/src/main/java/to/bitkit/data/SettingsStore.kt, app/src/main/java/to/bitkit/data/WidgetsStore.kt
Closes #314 
[FIGMA](https://www.figma.com/design/ltqvnKiejWj0JQiqtDf2JJ/Bitkit-Wallet?node-id=33495-110336&t=zYKPFgSGRa7q2J0F-4)
- Set default visibility as true
- Display Prices, Blocks, and Headlines as default in a fresh wallet
https://github.com/user-attachments/assets/855eee57-6360-48d0-be73-05a5bb4cea34
How to reproduce: 
1. Create a fresh wallet
2. Should display the widgets Prices, Blocks, and Headlines
=> fix: Widgets default settings

app/src/main/java/to/bitkit/fcm/WakeNodeWorker.kt, app/src/main/java/to/bitkit/models/NewTransactionSheetDetails.kt, app/src/main/java/to/bitkit/repositories/ActivityRepo.kt, app/src/main/java/to/bitkit/repositories/LightningRepo.kt, app/src/main/java/to/bitkit/repositories/WalletRepo.kt, app/src/main/java/to/bitkit/ui/screens/wallets/activity/ActivityDetailScreen.kt, app/src/main/java/to/bitkit/ui/sheets/NewTransactionSheet.kt, app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt, app/src/test/java/to/bitkit/repositories/ActivityRepoTest.kt
Replaces #315 
This PR fixes the bug of the send sheet displaying the data of the previous activity
The sheet is displayed before the onChain activity is added, so the app can't find the correct data to display.
https://github.com/user-attachments/assets/910a7f17-7f8e-4826-ae67-300b97a47125
Tested:
=> Get transaction detail by tx id

.github/workflows/ci.yml, .github/workflows/lint.yml, app/src/test/java/to/bitkit/repositories/ActivityRepoTest.kt
This PR allows running the tests and lint on all PRs instead of just the ones to master
`n/a`
`n/a`
=> Run tests and Lint on all PRs

app/src/main/java/to/bitkit/ui/screens/scanner/QrScanningScreen.kt
Make ScanPrompt, QRDialog, QRInput visible as resource-id. Similar case as in https://github.com/synonymdev/bitkit-android/pull/320.
=> Make ScanPrompt, QRDialog, QRInput visible

app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt
Related to #49
- The `Event.PaymentSuccessful` doesn't  return the amount sent, so as a temporary solution, the app can get it from the activity list
- Use sendLightning data to display the success screen with the correct amount
- Save the payment hash in processedPayments so it doesn't display the same success sheet twice
- reset processedPayments on next payment
https://github.com/user-attachments/assets/d875c3a5-3736-433d-b007-f3a5768b9d71
Tested:
=> fix: Display LN amount in send success sheet

app/src/main/java/to/bitkit/ui/settings/advanced/RgsServerScreen.kt
Update keyboard options on rgs screen to have ImeAction.Done. Similar to https://github.com/synonymdev/bitkit-android/pull/323.
Before:
After:
=> Update keyboard options on rgs screen to have ImeAction.Done

app/src/main/java/to/bitkit/ui/screens/wallets/send/SendQuickPayScreen.kt, app/src/main/java/to/bitkit/ui/sheets/SendSheet.kt, app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt, app/src/main/java/to/bitkit/viewmodels/QuickPayViewModel.kt
Closes https://github.com/synonymdev/bitkit-android/pull/331#pullrequestreview-3175719362
This PR removes backstack on success navigation. Also fix QuickPay success screen
https://github.com/user-attachments/assets/56ecf747-5159-454e-8635-14dad0b8c02e
https://github.com/user-attachments/assets/e75b4c3f-7b9d-4583-8d23-cc50a8ce7b35
https://github.com/user-attachments/assets/ac491371-3210-47de-bb9e-31fbef0f4b2c
Tested:
Try to swipe back in:
=> fix: Remove backstack on success navigation

.github/workflows/e2e.yml
The [script](https://github.com/synonymdev/bitkit-e2e-tests/blob/main/ci_run_android.sh) lives in `bitkit-e2e-tests` repo and it adds necessary adb configs and enables logcat that is added to artifacts in case tests fail.
=> Adjust e2e workflow to run tests using script

app/src/main/java/to/bitkit/ui/components/InactivityTracker.kt
closes #332 
Related to #268 
This PR replaces the "require pin on idle" logic with one that requires it every time the app is resumed
[Slack thread](https://synonymworkspace.slack.com/archives/C07BJ7DNPCG/p1754647706979969)
https://github.com/user-attachments/assets/c86cd227-aea6-4e05-9a28-36ced8d1fb92
Tested:
- Enable the feature -> but the app in the background -> should require the pin
- Disables the feature -> but the app in the background -> should not require the pin
=> Simplify requires pin on idle logic

app/src/main/java/to/bitkit/data/backup/VssBackupClient.kt, app/src/main/java/to/bitkit/env/Env.kt, app/src/main/java/to/bitkit/services/LightningService.kt
This PR uses the new staging services to enable secured backups using [vss-server](https://github.com/ovitrif/vss-server) with JWT authentication enabled by the new [lnurl-auth-server](https://github.com/synonymdev/lnurl-auth-server/) backend service for issuing JWT tokens based on the contract expected by ldk-node and [vss-rust-client](https://github.com/synonymdev/vss-rust-client-ffi).
- Test with new wallet (do not expect old wallets to work):
- crate wallet > fund > transfer to spending
- send onchain once
- send lightning once
- remove all suggestion cards but one
- remove all widgets
- settings > backup or restore > save seed > reset and restore wallet
- use seed to restore
- expect wallet to restore correctly:
- expect ldk-node restore success: channel + activity history correct
- …
=> feat: use new staging vss auth services

app/src/main/java/to/bitkit/ui/utils/Transitions.kt
- Forward Navigation (enter/exit):
- New screen slides in from the right edge (slideInHorizontally with fullWidth offset)
- Current screen slides out partially to the left (-fullWidth / 3) with a slight fade, mimicking how iOS keeps the previous screen partially visible
- Back Navigation (popEnter/popExit):
- Previous screen slides back in from its partially visible position
- Current screen slides out completely to the right
- Animation Specs
- Uses 300ms duration (closer to iOS timing)
- FastOutSlowInEasing for more natural iOS-like easing
- Added fade effects to simulate the iOS layering effect
https://github.com/user-attachments/assets/afed249e-7b8a-40f6-a74b-42680bc504fb
- Browse through the app and look for transition inconsistencies
=> Smooth default transition

app/detekt-baseline.xml, app/src/androidTest/java/to/bitkit/ui/screens/wallets/send/SendAmountContentTest.kt, app/src/main/java/to/bitkit/repositories/LightningRepo.kt, app/src/main/java/to/bitkit/services/LightningService.kt, app/src/main/java/to/bitkit/ui/screens/wallets/receive/EditInvoiceScreen.kt, app/src/main/java/to/bitkit/ui/screens/wallets/receive/ReceiveAmountScreen.kt, app/src/main/java/to/bitkit/ui/screens/wallets/send/SendAmountScreen.kt, app/src/test/java/to/bitkit/repositories/LightningRepoTest.kt
This PR refactors the receive amount screen in the CJIT flow to use the custom numeric keyboard and fixes a few other UI issues in the screen as well as on the edit invoice screen from the receive sheet.
Changes:
- feat(receive): change unit on amount click
- fix(receive): push keyboard and buttons to the bottom
- fix: send amount test tags in compose tests
- feat(receive): use custom keyboard in cjit flow
- refactor: add optional channelConfig param to `openChannel`
**CJIT Amount Screen**
| Before | After | After - Small Screen |
| - | - | - |
| <img width="314" src="https://github.com/user-attachments/assets/cde46125-7b87-4499-bc28-3958d3284604" /> | <img width="314" src="https://github.com/user-attachments/assets/7698add0-4320-4439-8622-46ade8930db2" /> | <img width="256" …
=> feat(receive): use custom keyboard in cjit flow

app/src/main/java/to/bitkit/repositories/LightningRepo.kt, app/src/main/java/to/bitkit/repositories/WalletRepo.kt, app/src/main/java/to/bitkit/services/CoreService.kt, app/src/main/java/to/bitkit/services/LightningService.kt, app/src/main/java/to/bitkit/ui/screens/wallets/receive/ReceiveSheet.kt, app/src/main/java/to/bitkit/viewmodels/BlocktankViewModel.kt, app/src/main/java/to/bitkit/viewmodels/WalletViewModel.kt, app/src/test/java/to/bitkit/repositories/LightningRepoTest.kt, app/src/test/java/to/bitkit/repositories/WalletRepoTest.kt, app/src/test/java/to/bitkit/ui/WalletViewModelTest.kt
This PR fixes all known issues related to geo blocking when node has external (non-LSP) peer connection.
Changes:
- fix(wallet): hide transfer to spending when geoblocked
- refactor: replace hasChannelsReady with canReceive
- fix(receive): block LN receive when when geoblocked if having no lsp channels ready
- fix(receive): enable LN receive and QR only when having channels ready
- fix(receive): refresh geoblock state on each receive sheet open
- fix(receive): enable LN toggle when having external node even if geoblocked
| Before | After |
| - | - |
| <video src="https://github.com/user-attachments/assets/77b46365-fc51-49ef-8e44-75fb7438722a"> | <video src="https://github.com/user-attachments/assets/dfa9aec8-3931-45f7-b5eb-3310e894dcea"> |
**Test:**
1. Use VPN to set location to a …
=> fix(receive): geo block issues with channels to external node

app/src/main/java/to/bitkit/ui/ContentView.kt, app/src/main/java/to/bitkit/ui/components/TabBar.kt, app/src/main/java/to/bitkit/ui/screens/wallets/HomeNav.kt, app/src/main/java/to/bitkit/ui/screens/wallets/HomeScreen.kt, app/src/main/java/to/bitkit/ui/screens/wallets/SavingsWalletScreen.kt, app/src/main/java/to/bitkit/ui/screens/wallets/SpendingWalletScreen.kt, app/src/main/java/to/bitkit/ui/screens/wallets/activity/utils/PreviewItems.kt
This PR fixes the logic to determine when to display the empty view on the savings & spending wallet screens so it doesn't show if there is existing activity, even if the respective balance is zero. It also hides the transfer-to-spending button if geo blocked.
Changes:
+ feat(spending): do not show empty view for 0 balance with existing activity
+ feat(savings): hide transfer to spending if geo blocked
+ feat(savings): do not show empty view for 0 balance with existing activity
Test:
- Regression test with fresh wallet that the empty views are shown as expected on savings and spendings screen, then check that they're hidden once there is balance and/or activity.
=> fix(wallet): fix savings & spending screens ui logic

app/src/main/java/to/bitkit/models/BalanceState.kt, app/src/main/java/to/bitkit/repositories/LightningRepo.kt, app/src/main/java/to/bitkit/repositories/WalletRepo.kt, app/src/main/java/to/bitkit/services/CoreService.kt, app/src/main/java/to/bitkit/services/LightningService.kt, app/src/main/java/to/bitkit/ui/screens/transfer/external/ExternalNodeViewModel.kt, app/src/main/java/to/bitkit/ui/screens/wallets/send/SendAmountScreen.kt, app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt, app/src/main/java/to/bitkit/viewmodels/TransferViewModel.kt, app/src/test/java/to/bitkit/repositories/LightningRepoTest.kt, app/src/test/java/to/bitkit/repositories/WalletRepoTest.kt
Closes #324 
- cache available on-chain sendable amount
- use cached value in send and transfer flow
- display reserve amount warning also for on-chain
- implement sendMax in on-chain send
[send.webm](https://github.com/user-attachments/assets/fa0687ad-3799-4a59-8bae-d95e068e4a8b)
[transfer.webm](https://github.com/user-attachments/assets/1ea463b1-7869-4f23-a332-b185eaf8152f)
Make sure you have some confirmed balance, I lost some time debugging until I realized it
- Send flow > click in available amount
- Transfer flor > click in max
=> Reserve a fee amount when trying to sent all on-chain balance

app/detekt-baseline.xml, app/src/main/java/to/bitkit/data/SettingsStore.kt, app/src/main/java/to/bitkit/env/Env.kt, app/src/main/java/to/bitkit/models/ElectrumServer.kt, app/src/main/java/to/bitkit/repositories/LightningRepo.kt, app/src/main/java/to/bitkit/services/LightningService.kt, app/src/main/java/to/bitkit/ui/components/Button.kt, app/src/main/java/to/bitkit/ui/components/TextInput.kt, app/src/main/java/to/bitkit/ui/onboarding/TermsOfUseScreen.kt, app/src/main/java/to/bitkit/ui/settings/advanced/ElectrumConfigScreen.kt, app/src/main/java/to/bitkit/ui/settings/advanced/ElectrumConfigViewModel.kt, app/src/test/java/to/bitkit/repositories/LightningRepoTest.kt
This PR refactors the electrum server config to use a plain url string as starting point instead of a complex data model.
**Changes:**
- refactor: normalize button types params and logic
- refactor: use url string for electrum server config
- refactor: extract const for PRIVACY_POLICY_URL
- fix: check to enable connect button after reset to default
- fix: start cursor at end of text in filled input fields
https://github.com/user-attachments/assets/5ff1cfc6-35e1-483e-b06b-55227318f600
**Test:**
2. uninstall old app
3. restore existing wallet → expect success 
4. settings → advanced → electrum
5. enter details for local electrum server (use [bitkit-docker](https://github.com/ovitrif/bitkit-docker?tab=readme-ov-file#electrum-server))
- once done on host input tap IME button → expect cursor …
=> refactor: use url string for electrum server config

app/src/main/java/to/bitkit/ui/screens/wallets/HomeViewModel.kt
isTimeOutOver didn't pass on fresh wallet because the value is initialized as zero
https://github.com/user-attachments/assets/1cfb2604-5448-436d-acc4-711d127c99e7
- New wallet -> receive $500 USD > should display warning
=> fix: High Balance warning time out calculation for fresh wallets
